export const SUBJECTS: { [key: string]: any } = {
  PESSOAS: {
    name: "Pessoas",
    description: "Cadastro de pessoas físicas e jurídicas",
    columns: [
      { name: "CODIGO", required: true, type: "numeric", maxLength: 9 },
      { name: "NOME", required: true, type: "text", maxLength: 100 },
      { name: "FANTASIA", required: true, type: "text", maxLength: 50 },
      { name: "TIPO_PESSOA", required: true, type: "enum", values: ["FISICA", "JURIDICA"] },
      { name: "CNPJ_CPF", required: false, type: "document" },
      { name: "NUMERO_RG", required: false, type: "text" },
      { name: "DATA_EMISSAO_RG", required: false, type: "date", format: "dd-MM-yyyy" },
      { name: "ORGAO_EMISSAO_RG", required: false, type: "text", maxLength: 6 },
      { name: "INSCRICAO_ESTADUAL", required: false, type: "text", maxLength: 25 },
      { name: "INSCRICAO_MUNICIPAL", required: false, type: "text", maxLength: 16 },
      { name: "TIPO_MERCADO", required: false, type: "enum", values: ["INTERNO", "EXTERNO"] },
      {
        name: "TIPO_ATIVIDADE",
        required: false,
        type: "enum",
        values: [
          "INDUSTRIA",
          "COMERCIO",
          "DISTRIBUIDOR",
          "TRR",
          "EXTRACAO_MINERAL_OUTROS",
          "INDUSTRIA_TRANSPORTE",
          "PRODUTOR_RURAL",
          "PRESTADOR_SERVICO",
          "ATIVIDADE_FINANCEIRA",
          "ATIVIDADE_IMOBILIARIA",
          "COOPERATIVA",
          "SOCIEDADE_SEGURADORAS",
          "DISTRIBUIDOR_ENERGIA",
          "PRESTADOR_SERVICO_COMUNICACAO",
          "OUTROS",
        ],
      },
      {
        name: "BENEFICIO_FISCAL",
        required: false,
        type: "enum",
        values: ["NAO_POSSUI", "ZONA_FRANCA_MANAUS", "ZONA_FRANCA", "AREA_LIVRE_COMERCIO", "AMAZONIA_OCIDENTAL"],
      },
      { name: "SUFRAMA", required: false, type: "text", maxLength: 10 },
      { name: "VALIDADE_SUFRAMA", required: false, type: "date", format: "dd-MM-yyyy" },
      { name: "CEP", required: false, type: "numeric", maxLength: 8 },
      { name: "NUMERO_ENDERECO", required: false, type: "text", maxLength: 60 },
      { name: "COMPLEMENTO_ENDERECO", required: false, type: "text", maxLength: 200 },
      { name: "TELEFONE", required: false, type: "numeric", maxLength: 11 },
      { name: "EMAIL", required: false, type: "email", maxLength: 100 },
      { name: "DATA_NASCIMENTO", required: false, type: "date", format: "dd-MM-yyyy" },
      { name: "SITUACAO", required: true, type: "enum", values: ["ATIVO", "INATIVO"] },
      { name: "CONSIDERA_FORNECEDOR", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "CONSIDERA_CLIENTE", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "CONSIDERA_REPRESENTANTE", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "CONSIDERA_TRANSPORTADORA", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "CONSIDERA_FAVORECIDO", required: false, type: "enum", values: ["SIM", "NAO"] },
      {
        name: "CODIGO_REGIME_TRIBUTARIO",
        required: true,
        type: "enum",
        values: ["SIMPLES", "SIMPLES_EXCESSO_SUBLIMITE", "NORMAL", "REGIME_ESPECIAL_TRIBUTACAO"],
      },
      {
        name: "MICRO_EMPRESA",
        required: false,
        type: "enum",
        values: ["ESTIMATIVA", "SOCIEDADE", "COOPERATIVA", "MEI", "ME_EPP"],
      },
      { name: "CONTRIBUINTE_ICMS", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "PESSOA_INDUSTRIA", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "RAMO_ATIVIDADE", required: false, type: "text", maxLength: 5 },
      { name: "EMAIL_NFE", required: false, type: "email_multiple", maxLength: 100 },
    ],
  },
  CLIENTE: {
    name: "Cliente (Especialização Comercial)",
    description: "Especialização comercial de clientes",
    columns: [
      { name: "EMPRESA", required: true, type: "numeric" },
      { name: "FILIAL", required: true, type: "numeric" },
      { name: "CODIGO_CLIENTE", required: true, type: "numeric" },
      { name: "CONDICAO_PAGAMENTO", required: false, type: "text" },
      { name: "REPRESENTANTE", required: false, type: "text" },
      { name: "TRANSPORTADORA", required: false, type: "text" },
      { name: "CONSUMIDOR_FINAL", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "SITUACAO", required: true, type: "enum", values: ["ATIVO", "INATIVO"] },
    ],
  },
  PRODUTOS: {
    name: "Produtos",
    description: "Cadastro de produtos",
    columns: [
      { name: "Código", required: true, type: "text", maxLength: 23 },
      { name: "Descrição", required: true, type: "text", maxLength: 120 },
      { name: "GTIN unidade tributável", required: false, type: "text", maxLength: 14 },
      { name: "Situação", required: true, type: "enum", values: ["ATIVO", "INATIVO"] },
      { name: "Peso líquido (kg)", required: false, type: "decimal", maxLength: 13 },
      { name: "Peso bruto (kg)", required: false, type: "decimal", maxLength: 13 },
      { name: "Comprimento (cm)", required: false, type: "decimal", maxLength: 13 },
      { name: "Largura (cm)", required: false, type: "decimal", maxLength: 13 },
      { name: "Altura (cm)", required: false, type: "decimal", maxLength: 13 },
      { name: "Código da marca", required: false, type: "text", maxLength: 10 },
      { name: "Código da empresa", required: true, type: "numeric", maxLength: 4 },
      { name: "Código da família", required: true, type: "numeric", maxLength: 6 },
      { name: "Pode ser vendido", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "Número do registro na Anvisa", required: false, type: "text", maxLength: 13 },
      { name: "Código da unidade de medida de venda", required: false, type: "text", maxLength: 6 },
      { name: "Código do produto ANP", required: false, type: "numeric", maxLength: 19 },
      { name: "Descrição do produto conforme ANP", required: false, type: "text", maxLength: 95 },
      {
        name: "Origem fiscal da mercadoria",
        required: false,
        type: "enum",
        values: ["0", "1", "2", "3", "4", "5", "6", "7", "8"],
      },
      {
        name: "Tipo do produto para impostos",
        required: false,
        type: "enum",
        values: [
          "NAO_CLASSIFICADO",
          "MERCADORIAS",
          "MATERIAS_PRIMAS",
          "PRODUTOS_INTERMEDIARIOS",
          "MATERIAIS_EMBALAGEM",
          "PRODUTOS_MANUFATURADOS",
          "EM_FABRICACAO",
          "SUBPRODUTO",
          "MATERIAL_USO_CONSUMO",
          "ATIVO_IMOBILIZADO",
          "SERVICOS",
          "OUTROS_INSUMOS",
          "OUTRAS",
        ],
      },
      {
        name: "Controlar ICMS ST Substituído e FCI Comércio pelo método do estoque PEPS",
        required: false,
        type: "enum",
        values: ["SIM", "NAO"],
      },
      { name: "Especificador de substituição tributária", required: false, type: "numeric", maxLength: 7 },
      { name: "NCM", required: false, type: "numeric", maxLength: 8 },
      { name: "Pode ser requisitado", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "Preço de custo", required: false, type: "decimal", maxLength: 15 },
      { name: "Código da unidade de medida de estoque", required: false, type: "text", maxLength: 6 },
      { name: "Depósito - Código da filial", required: false, type: "numeric", maxLength: 4 },
      { name: "Depósito - Código do depósito", required: false, type: "text", maxLength: 10 },
      { name: "Código da unidade de medida auxiliar de estoque", required: false, type: "text", maxLength: 6 },
      { name: "Pode ser comprado", required: false, type: "enum", values: ["SIM", "NAO"] },
    ],
  },
  SERVICO: {
    name: "Serviços",
    description: "Cadastro de serviços",
    columns: [
      { name: "EMPRESA", required: true, type: "numeric", maxLength: 4 },
      { name: "FAMILIA", required: true, type: "numeric", maxLength: 6 },
      { name: "CODIGO", required: true, type: "text", maxLength: 14 },
      { name: "DESCRICAO", required: true, type: "text", maxLength: 70 },
      { name: "COMPLEMENTO", required: false, type: "text", maxLength: 250 },
      { name: "CODIGO_UNIDADE_MEDIDA", required: true, type: "text", maxLength: 6 },
      { name: "QUANTIDADE_PADRAO", required: false, type: "decimal", maxLength: 14 },
      { name: "FILIAL", required: false, type: "numeric", maxLength: 5 },
      { name: "TRANSPORTADORA", required: false, type: "numeric", maxLength: 9 },
      { name: "TIPO_ENERGIA", required: false, type: "enum", values: ["MONOFASICO", "BIFASICO", "TRIFASICO"] },
      { name: "SITUACAO", required: true, type: "enum", values: ["ATIVO", "INATIVO"] },
    ],
  },
  SALDO_INICIAL_ESTOQUE: {
    name: "Saldo Inicial de Estoque",
    description: "Importação de saldos iniciais de estoque",
    columns: [
      { name: "CODIGO_EMPRESA", required: true, type: "numeric" },
      { name: "CODIGO_FILIAL", required: true, type: "numeric" },
      { name: "CODIGO_PRODUTO", required: true, type: "text", maxLength: 23 },
      { name: "CODIGO_DEPOSITO", required: true, type: "text" },
      { name: "CODIGO_TRANSACAO_ESTOQUE", required: true, type: "text" },
      { name: "QUANTIDADE", required: true, type: "decimal" },
      { name: "VALOR", required: true, type: "decimal" },
      { name: "NUMERO_SERIE", required: false, type: "text" },
      { name: "CODIGO_LOTE", required: false, type: "text" },
      { name: "DATA_FABRICACAO_LOTE_SERIE", required: false, type: "date" },
      { name: "DATA_VALIDADE_LOTE_SERIE", required: false, type: "date" },
    ],
  },
  REPRESENTANTE: {
    name: "Representante (Especialização Comercial)",
    description: "Especialização comercial de representantes",
    columns: [
      { name: "CODIGO_REPRESENTANTE", required: true, type: "numeric" },
      { name: "CODIGO_EMPRESA", required: true, type: "numeric" },
      { name: "CODIGO_FILIAL", required: true, type: "numeric" },
      {
        name: "CATEGORIA_REPRESENTANTE",
        required: true,
        type: "enum",
        values: [
          "MATRIZ",
          "REPRESENTANTE",
          "VENDEDOR",
          "GERENTE",
          "DISTRIBUIDOR",
          "DIRETOR",
          "CREDIARISTA",
          "CAIXA",
          "PRESIDENTE",
          "SUPERVISOR",
          "GERENTE_SERVICOS",
          "ANALISTA_SERVICOS",
          "GESTOR_CREDIARIO",
          "ASSISTENTE_ADM",
          "GERENTE_REGIONAL",
          "OPERADOR_TELEMARKETING",
          "SUB_GERENTE",
        ],
      },
    ],
  },
  SITUACAO_NCM: {
    name: "Situação NCM",
    description: "Situação dos códigos NCM",
    columns: [
      { name: "Código", required: true, type: "numeric", maxLength: 8 },
      { name: "Situação", required: true, type: "enum", values: ["ATIVO", "INATIVO"] },
    ],
  },
  TABELA_PRECO_VENDA: {
    name: "Tabela de Preço de Venda",
    description: "Tabela de preços para venda",
    columns: [
      { name: "TIPO_ITEM", required: true, type: "enum", values: ["VP", "VS"] },
      { name: "CODIGO", required: true, type: "text" },
      { name: "UNIDADE_MEDIDA", required: true, type: "text" },
      { name: "CONDICAO_PAGAMENTO", required: false, type: "text" },
      { name: "QTD_MAXIMA", required: false, type: "numeric" },
      { name: "VALOR_BASE", required: true, type: "decimal" },
      { name: "PERCENTUAL_DESCONTO", required: false, type: "decimal" },
      { name: "PERCENTUAL_COMISSAO", required: false, type: "decimal" },
      { name: "OBSERVACAO", required: false, type: "text" },
    ],
  },
  TABELA_PRECO_COMPRA: {
    name: "Tabela de Preço de Compra",
    description: "Tabela de preços para compra",
    columns: [
      { name: "TIPO", required: true, type: "enum", values: ["VP", "VS"] },
      { name: "COD_ITEM", required: true, type: "text", maxLength: 23 },
      { name: "COD_ITEM_FORNECEDOR", required: false, type: "text", maxLength: 30 },
      { name: "UNIDADE_MEDIDA", required: true, type: "text", maxLength: 6 },
      { name: "COD_CONDICAO_PAGAMENTO", required: false, type: "text", maxLength: 6 },
      { name: "QUANTIDADE_MAXIMA", required: false, type: "numeric" },
      { name: "PRECO_BASE", required: true, type: "decimal" },
      { name: "PERCENTUAL_DESCONTO", required: false, type: "decimal" },
      { name: "OBSERVACAO", required: false, type: "text", maxLength: 250 },
    ],
  },
  TITULOS_PAGAR: {
    name: "Títulos a Pagar",
    description: "Importação de títulos a pagar",
    columns: [
      { name: "EMPRESA", required: true, type: "numeric", maxLength: 4 },
      { name: "FILIAL", required: true, type: "numeric", maxLength: 4 },
      { name: "NUMERO_TITULO", required: true, type: "text", maxLength: 15 },
      { name: "TIPO_TITULO", required: true, type: "text", maxLength: 3 },
      { name: "FORNECEDOR", required: false, type: "text", maxLength: 15 },
      { name: "CNPJ_CPF", required: false, type: "document" },
      { name: "FAVORECIDO", required: false, type: "text", maxLength: 15 },
      { name: "VALOR", required: true, type: "decimal", maxLength: 15 },
      { name: "FORMA_PAGAMENTO", required: false, type: "text", maxLength: 15 },
      { name: "TRANSACAO", required: true, type: "text", maxLength: 5 },
      { name: "DATA_EMISSAO", required: true, type: "date", format: "dd/MM/yyyy" },
      { name: "DATA_ENTRADA", required: true, type: "date", format: "dd/MM/yyyy" },
      { name: "VENCIMENTO", required: true, type: "date", format: "dd/MM/yyyy" },
      { name: "PRORROGA_JUROS", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "PERCENTUAL_DESCONTO", required: false, type: "decimal", maxLength: 5 },
      { name: "VALOR_DESCONTO", required: false, type: "decimal", maxLength: 15 },
      { name: "PORTADOR", required: true, type: "text", maxLength: 4 },
      { name: "CARTEIRA", required: true, type: "text", maxLength: 2 },
      { name: "TIPO_JUROS", required: false, type: "enum", values: ["SIMPLES", "COMPOSTO"] },
      { name: "PERCENTUAL_JUROS", required: false, type: "decimal", maxLength: 5 },
      { name: "PERCENTUAL_MULTA", required: false, type: "decimal", maxLength: 5 },
      { name: "MOEDA", required: true, type: "text", maxLength: 3 },
      { name: "COTACAO_MOEDA", required: false, type: "decimal", maxLength: 19 },
      { name: "OBSERVACAO", required: true, type: "text", maxLength: 200 },
      { name: "CONTA_FINANCEIRA", required: false, type: "text", maxLength: 19 },
      { name: "CENTRO_CUSTO", required: false, type: "text", maxLength: 9 },
    ],
  },
  TITULOS_RECEBER: {
    name: "Títulos a Receber",
    description: "Importação de títulos a receber",
    columns: [
      { name: "EMPRESA", required: true, type: "numeric", maxLength: 4 },
      { name: "FILIAL", required: true, type: "numeric", maxLength: 4 },
      { name: "NUMERO_TITULO", required: true, type: "text", maxLength: 15 },
      { name: "TIPO_TITULO", required: true, type: "text", maxLength: 3 },
      { name: "CLIENTE", required: false, type: "text", maxLength: 15 },
      { name: "CNPJ_CPF", required: false, type: "document" },
      { name: "SACADO", required: false, type: "text", maxLength: 15 },
      { name: "VALOR", required: true, type: "decimal", maxLength: 15 },
      { name: "FORMA_PAGAMENTO", required: false, type: "text", maxLength: 15 },
      { name: "TRANSACAO", required: true, type: "text", maxLength: 5 },
      { name: "DATA_EMISSAO", required: true, type: "date", format: "dd/MM/yyyy" },
      { name: "DATA_ENTRADA", required: true, type: "date", format: "dd/MM/yyyy" },
      { name: "VENCIMENTO", required: true, type: "date", format: "dd/MM/yyyy" },
      { name: "PRORROGA_JUROS", required: false, type: "enum", values: ["SIM", "NAO"] },
      { name: "PERCENTUAL_DESCONTO", required: false, type: "decimal", maxLength: 5 },
      { name: "VALOR_DESCONTO", required: false, type: "decimal", maxLength: 15 },
      { name: "PORTADOR", required: true, type: "text", maxLength: 4 },
      { name: "CARTEIRA", required: true, type: "text", maxLength: 2 },
      { name: "TIPO_JUROS", required: false, type: "enum", values: ["SIMPLES", "COMPOSTO"] },
      { name: "PERCENTUAL_JUROS", required: false, type: "decimal", maxLength: 5 },
      { name: "PERCENTUAL_MULTA", required: false, type: "decimal", maxLength: 5 },
      { name: "MOEDA", required: false, type: "text", maxLength: 3 },
      { name: "COTACAO_MOEDA", required: false, type: "decimal", maxLength: 19 },
      { name: "OBSERVACAO", required: true, type: "text", maxLength: 200 },
      { name: "NUMERO_CHEQUE", required: false, type: "text", maxLength: 10 },
      { name: "NOSSO_NUMERO", required: false, type: "text", maxLength: 20 },
      { name: "CONTA_FINANCEIRA", required: false, type: "text", maxLength: 19 },
      { name: "CENTRO_CUSTO", required: false, type: "text", maxLength: 9 },
    ],
  },
  INFORMACOES_FISCAIS: {
    name: "Informações Fiscais (PEPS)",
    description: "Informações fiscais para controle PEPS",
    columns: [
      { name: "EMPRESA", required: true, type: "numeric" },
      { name: "FILIAL", required: true, type: "numeric" },
      { name: "PRODUTO", required: true, type: "text", maxLength: 23 },
      { name: "QUANTIDADE", required: true, type: "decimal" },
      { name: "DATA DE ENTRADA", required: true, type: "datetime", format: "dd/MM/yyyy HH:mm:ss" },
      { name: "BASE ICMS", required: true, type: "decimal" },
      { name: "PERCENTUAL ICMS", required: true, type: "decimal" },
      { name: "VALOR ICMS", required: true, type: "decimal" },
      { name: "BASE ICMS ST", required: true, type: "decimal" },
      { name: "PERCENTUAL ICMS ST", required: true, type: "decimal" },
      { name: "VALOR ICMS ST", required: true, type: "decimal" },
      { name: "BASE FCP", required: true, type: "decimal" },
      { name: "PERCENTUAL FCP", required: true, type: "decimal" },
      { name: "VALOR FCP", required: true, type: "decimal" },
      { name: "BASE FCP ST", required: true, type: "decimal" },
      { name: "PERCENTUAL FCP ST", required: true, type: "decimal" },
      { name: "VALOR FCP ST", required: true, type: "decimal" },
      { name: "CÓDIGO DA FCI", required: false, type: "text", maxLength: 36 },
      {
        name: "ORIGEM DA MERCADORIA",
        required: false,
        type: "enum",
        values: ["0", "1", "2", "3", "4", "5", "6", "7", "8"],
      },
    ],
  },
  CONVERSAO_UNIDADE_MEDIDA: {
    name: "Conversão Unidade de Medida",
    description: "Conversões entre unidades de medida",
    columns: [
      { name: "Código da empresa", required: true, type: "numeric" },
      { name: "Código do produto", required: true, type: "text" },
      { name: "Código da pessoa", required: false, type: "text" },
      { name: "Código da unidade de medida de origem", required: true, type: "text" },
      { name: "Código da unidade de medida de destino", required: true, type: "text" },
      { name: "Operador de conversão", required: true, type: "enum", values: ["MULTIPLICAR", "DIVIDIR"] },
      { name: "Valor para conversão", required: true, type: "decimal" },
    ],
  },
  DEPOSITO: {
    name: "Depósito",
    description: "Cadastro de depósitos",
    columns: [
      { name: "EMPRESA", required: true, type: "numeric" },
      { name: "FILIAL", required: true, type: "numeric" },
      { name: "CODIGO", required: true, type: "text" },
      { name: "DESCRICAO", required: true, type: "text" },
      { name: "ABREVIATURA", required: true, type: "text" },
      { name: "UTILIZA_COMPRA", required: true, type: "enum", values: ["SIM", "NAO"] },
      { name: "UTILIZA_VENDA", required: true, type: "enum", values: ["SIM", "NAO"] },
      { name: "OBSERVACAO", required: false, type: "text" },
      { name: "SITUACAO", required: true, type: "enum", values: ["ATIVO", "INATIVO"] },
    ],
  },
  ENGENHARIAS: {
    name: "Engenharias",
    description: "Estruturas de engenharia de produtos",
    columns: [
      { name: "CODIGO_EMPRESA", required: true, type: "numeric" },
      { name: "CODIGO_FILIAL", required: true, type: "numeric" },
      { name: "CODIGO_SKU_PRODUCAO", required: true, type: "text" },
      { name: "CODIGO_ROTEIRO", required: false, type: "text" },
      { name: "PERCENTUAL_PERDA_SKU_CONSUMO", required: false, type: "decimal" },
      { name: "CODIGO_ESTAGIO", required: true, type: "text" },
      { name: "CODIGO_SKU_CONSUMO", required: false, type: "text" },
      { name: "QUANTIDADE_SKU_CONSUMO", required: false, type: "decimal" },
      { name: "PERCENTUAL_PERDA_SKU_PRODUCAO", required: false, type: "decimal" },
      { name: "TIPO_MOVIMENTO_SKU_CONSUMO", required: false, type: "enum", values: ["AUTOMATICO", "MANUAL"] },
      {
        name: "FATOR_UTILIZACAO_SKU_CONSUMO",
        required: false,
        type: "enum",
        values: ["PROPORCIONAL", "FREQUENCIAL", "PERCENTUAL", "FIXO"],
      },
      { name: "LOTE_FREQUENCIAL_SKU_CONSUMO", required: false, type: "decimal" },
      { name: "CODIGO_OPERACAO", required: false, type: "text" },
      { name: "CODIGO_RECURSO", required: false, type: "text" },
    ],
  },
  PLANO_FINANCEIRO: {
    name: "Plano Financeiro",
    description: "Plano de contas financeiro",
    columns: [
      { name: "codigoconta", required: true, type: "numeric", maxLength: 9 },
      { name: "classificacao", required: true, type: "text" },
      { name: "descricao", required: true, type: "text", maxLength: 250 },
      { name: "abreviatura", required: true, type: "text", maxLength: 20 },
      { name: "codigodotipofinanceiro", required: true, type: "numeric" },
      { name: "analiticasintetica", required: true, type: "enum", values: ["ANALITICA", "SINTETICA"] },
      { name: "natureza", required: true, type: "enum", values: ["DEVEDORA", "CREDORA", "AMBAS"] },
      { name: "nivel", required: true, type: "numeric" },
      { name: "contacontabilvinculada", required: false, type: "text" },
    ],
  },
  PLANO_CONTABIL: {
    name: "Plano Contábil",
    description: "Plano de contas contábil",
    columns: [
      { name: "codigoconta", required: true, type: "numeric", maxLength: 9 },
      { name: "classificacao", required: true, type: "text" },
      { name: "descricao", required: true, type: "text", maxLength: 250 },
      { name: "abreviatura", required: true, type: "text", maxLength: 20 },
      {
        name: "definicaodegrupo",
        required: true,
        type: "enum",
        values: ["ATIVO", "PASSIVO", "PATRIMONIO_LIQUIDO", "CONTAS_RESULTADO", "CONTAS_COMPENSACAO", "OUTROS"],
      },
      { name: "analiticasintetica", required: true, type: "enum", values: ["ANALITICA", "SINTETICA"] },
      { name: "natureza", required: true, type: "enum", values: ["DEVEDORA", "CREDORA", "AMBAS"] },
      { name: "nivel", required: true, type: "numeric" },
      { name: "formaderateio", required: true, type: "enum", values: ["SEM_RATEIO", "RATEIO_MANUAL"] },
      { name: "exigecontaauxiliar", required: true, type: "enum", values: ["SIM", "NAO"] },
      { name: "aceitalancamentomanual", required: true, type: "enum", values: ["SIM", "NAO"] },
    ],
  },
  CENTRO_CUSTO: {
    name: "Centro de Custo",
    description: "Centros de custo",
    columns: [
      { name: "codigodocentrodecusto", required: true, type: "numeric", maxLength: 9 },
      { name: "classificacao", required: true, type: "text" },
      { name: "descricao", required: true, type: "text", maxLength: 250 },
      { name: "abreviatura", required: true, type: "text", maxLength: 20 },
      { name: "analiticasintetica", required: true, type: "enum", values: ["ANALITICA", "SINTETICA"] },
      { name: "natureza", required: true, type: "enum", values: ["DEVEDORA", "CREDORA", "AMBAS"] },
      {
        name: "tipodocentrodecusto",
        required: true,
        type: "enum",
        values: ["OPERACIONAL_INDIRETO", "OPERACIONAL_DIRETO", "ADMINISTRATIVO", "COMERCIAL", "FINANCEIRO"],
      },
      { name: "nivel", required: true, type: "numeric" },
    ],
  },
}
